GET_IS_NOT_UPPORTED = {"msg":"GET is not supported"}, 404
NO_FILE_SELECTED = {"msg":"No file selected"}, 400
FILE_TYPE_IS_NOT_ALLOWED = {"msg":"This file type is not allowed"}, 400
REPORT_ID_EMPTY = {"msg":"Report id is empty"}, 400
COUNTRY_EMPTY = {"msg":"Country code is empty"}, 400
BUSINESS_RULE_EMPTY = {"msg":"Business rule is empty"}, 400
DATABASE_ERROR = {"msg":"Database error occured"}, 400
UPDATE_ERROR = {"msg":"No records updated"}, 400
NO_BUSINESS_RULE_FOUND = {"msg":"No Business Rule found"}, 404
INVALID_JSON = {"msg":"Invalid JSON data"}, 400
NO_USER_FOUND = {"msg":"No User found"}, 404
RESOURCE_EMPTY = {"msg":"Resource id is empty"}, 400
ROLE_EMPTY = {"msg":"Role id is empty"}, 400
DATA_NOT_FOUND = {"msg":"Data not found"}, 400
